CoffeeConsumption/Models/Consumption.cs
using System;

namespace CoffeeConsumption.Models
{
    public class Consumption
    {
        public int Id { get; set; }

        public int UserId { get; set; }

        public int CupId { get; set; }

        public DateTimeOffset BeverageTime { get; set; }

        public virtual Cup Cup { get; set; }

        public virtual User User { get; set; } 
    }
}

CoffeeConsumption/Models/Cup.cs
using System.Collections.Generic;

namespace CoffeeConsumption.Models
{
    public class Cup
    {
        public int Id { get; set; }

        public BeverageType Beverage { get; set; }

        public virtual ICollection<Consumption> Consumptions { get; set; }
    }

    public enum BeverageType
    {
        Coffee,
        Tea,
        Juice
    }
}

CoffeeConsumption/Models/OfficeContext.cs
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;

namespace CoffeeConsumption.Models
{
    public class OfficeContext : DbContext
    {
        static OfficeContext()
        {
            Database.SetInitializer(new OfficeInitializer());
        }

        public OfficeContext()
            : base("Name=OfficeContext")
        {
        }

        public DbSet<Cup> Cups { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Consumption> Consumptions { get; set; }
        
    }
}

CoffeeConsumption/Models/OfficeInitializer.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace CoffeeConsumption.Models
{
    public class OfficeInitializer : DropCreateDatabaseIfModelChanges<OfficeContext> 
    {
        protected override void Seed(OfficeContext context)
        {
            var cups = new List<Cup>
                {
                    new Cup {Beverage = BeverageType.Coffee},
                    new Cup {Beverage = BeverageType.Tea},
                    new Cup {Beverage = BeverageType.Juice}
                };
            cups.ForEach(s => context.Cups.Add(s));
            context.SaveChanges();

            var users = new List<User>
                {
                    new User {Name = "Tanya", Email = "t.arkhipova@svitla.com", Password = "1"},
                    new User {Name = "Igor", Email = "i.kesler@svitla.com", Password = "1"},
                    new User {Name = "Sasha", Email = "a.volkov@svitla.com", Password = "1"}
                };
            users.ForEach(s => context.Users.Add(s));
            context.SaveChanges();

            var consumptions = new List<Consumption>
                {
                    new Consumption {UserId = 1, CupId = 1, BeverageTime = DateTime.Now.AddDays(-1)},
                    new Consumption {UserId = 1, CupId = 2, BeverageTime = DateTime.Now.AddMinutes(-10)},
                    new Consumption {UserId = 2, CupId = 3, BeverageTime = DateTime.Now.AddDays(-2)}
                };
            consumptions.ForEach(s => context.Consumptions.Add(s));
            context.SaveChanges();
        }
    }
}

CoffeeConsumption/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CoffeeConsumption.Models
{
    public class User
    {
        public int Id { get; set; }

        public string Name { get; set; }

        [Required(ErrorMessage = "Login is required")]
        [EmailAddress(ErrorMessage = "Login should me a valid email address")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Password is required")]
        public string Password { get; set; }

        public virtual ICollection<Consumption> Consumptions { get; set; }
    }
}

CoffeeConsumption/Controllers/HomeController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using CoffeeConsumption.Managers;
using CoffeeConsumption.Models;
using Core;

namespace CoffeeConsumption.Controllers
{
    public class HomeController : Controller
    {
        private readonly OfficeContext db = new OfficeContext();

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult Login(User user)
        {
            var currentUser =
                db.Users.FirstOrDefault(
                    u =>
                    u.Email.ToLower()
                     .Equals(user.Email.ToLower()) && u.Password.ToLower().Equals(user.Password.ToLower()));
            if (currentUser != null)
            {
                SessionManager.SetCurrentUserID(currentUser.Id);
                var cups = db.Cups.ToList();
                return View("GetBeverage", cups);
            }
            return View("Login", user);
        }

        [HttpGet]
        public ActionResult GetBeverage()
        {
            var cups = db.Cups.ToList();
            return View("GetBeverage", cups);
        }
        
        [HttpPost]
        public ActionResult GetBeverage(Cup cup)
        {
            var userId = SessionManager.GetCurrentUserId();
            if (!userId.HasValue)
            {
                return RedirectToAction("Login", "Home");
            }
            var consumption = new Consumption
                {
                    UserId = userId.Value,
                    CupId = cup.Id,
                    BeverageTime = DateTime.Now
                };
            db.Consumptions.Add(consumption);
            db.SaveChanges();

            return Json(CCResponse.Succeded());
        }
    }
}

CoffeeConsumption/Controllers/ReportController.cs
using System.Web.Mvc;
using System.Linq;
using CoffeeConsumption.Managers;
using CoffeeConsumption.Models;
using Core;

namespace CoffeeConsumption.Controllers
{
    public class ReportController : Controller
    {
        private readonly OfficeContext db = new OfficeContext();

        [HttpGet]
        public ActionResult PersonalReport()
        {
            var currentUserId = SessionManager.GetCurrentUserId();
            if (!currentUserId.HasValue)
            {
                return RedirectToAction("Login", "Home");
            }
            var consumptions = db.Consumptions.Where(c => c.UserId == currentUserId.Value).ToList();
            return View("PersonalReport", consumptions);
        }

        [HttpGet]
        public ActionResult OfficeRatings()
        {
            return View(db.Consumptions.ToList());
        }

    }
}

CoffeeConsumption/Views/Home/GetBeverage.cshtml
@model List<CoffeeConsumption.Models.Cup>

@{
    ViewBag.Title = "Get beverage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/cc.getBeverage.js"></script>
<h2>GetBeverage</h2>

<ul style="padding-left: 0px">
@foreach (var item in Model)
{
    <li class="marginTop20px" style="display: inline-block">
        <a href="#" id="@(item.Beverage.ToString())SelectButton">
            <img src="~/Content/@(item.Beverage.ToString()).jpg" data-cupid="@item.Id" class="beverageButton" alt="@(item.Beverage.ToString())"/>
        </a>
    </li>
}
</ul>
<div class="textAlignCenter">
    <button class="button" value="Get" id="getButton">Get</button>
</div>

CoffeeConsumption/Views/Home/Login.cshtml
@model CoffeeConsumption.Models.User

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Login</h2>
<div>
    @using (Html.BeginForm("Login"))
    {
        @Html.ValidationSummary(true)
        <div class="marginTop20px" title="Set your email">
            <label>Login: </label>@Html.EditorFor(m => m.Email)
            @Html.ValidationMessageFor(m=> m.Email)
        </div>
        <div class="marginTop20px">
            <label>Password: </label>@Html.EditorFor(m => m.Password)
            @Html.ValidationMessageFor(m=> m.Password)
        </div>
        <div class="textAlignCenter">
            <button class="button" value="Login" id="loginButton">Login</button>
        </div>
    }
</div>

CoffeeConsumption/Views/Report/OfficeRatings.cshtml
@using CoffeeConsumption.Models
@model List<Consumption>

@{
    ViewBag.Title = "OfficeRatings";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>OfficeRatings</h2>

@foreach (var item in Model.GroupBy(c => c.UserId)
                  .Select(group => 
                        new { Id = group.Key,
                            Name = group.First().User.Name,
                              Cups = group.OrderByDescending(x => x.Id) })
                  .OrderByDescending(group => group.Cups.Count()))
{
    <div>
        <span>@item.Name drank @item.Cups.Count() cups</span>
    </div>
}

CoffeeConsumption/Views/Report/PersonalReport.cshtml
@using CoffeeConsumption.Models
@model IEnumerable<Consumption>

@{
    ViewBag.Title = "PersonalReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>PersonalReport</h2>

<h3>Today</h3>
@foreach (Consumption item in Model.Where(c=> c.BeverageTime > DateTime.Now.Date))
{
    <div>
        <img src="~/Content/@(item.Cup.Beverage.ToString()).jpg" title="@item.Cup.Beverage.ToString()" class="beverageImage"
             alt="@(item.Cup.Beverage.ToString())"/> <span>@item.Cup.Beverage.ToString() at @item.BeverageTime.ToString("hh:mm")</span>
    </div>
}
<h3>Yesterday</h3>
@foreach (Consumption item in Model.Where(c => DateTime.Now.AddDays(-1).Date < c.BeverageTime && c.BeverageTime < DateTime.Now.Date))
{
    <div>
        <img src="~/Content/@(item.Cup.Beverage.ToString()).jpg" title="@item.Cup.Beverage.ToString()" class="beverageImage"
             alt="@(item.Cup.Beverage.ToString())"/> <span>@item.Cup.Beverage.ToString() at @item.BeverageTime.ToString("hh:mm")</span>
    </div>
}
<h3>Earlier</h3>
@foreach (Consumption item in Model.Where(c => c.BeverageTime < DateTime.Now.AddDays(-1).Date))
{
    <div>
        <img src="~/Content/@(item.Cup.Beverage.ToString()).jpg" title="@item.Cup.Beverage.ToString()" class="beverageImage"
             alt="@(item.Cup.Beverage.ToString())"/> <span>@item.Cup.Beverage.ToString() on @item.BeverageTime.ToString("dd:MM:yy") at @item.BeverageTime.ToString("hh:mm")</span>
    </div>
}

CoffeeConsumption/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/styles.css" rel="stylesheet" type="text/css">
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/cc.main.js"></script>
    <script src="~/Scripts/cc.proxy.js"></script>
    <script type="text/javascript">
        $(function() {
            cc.urls = {};
            cc.urls.getBeverageUrl = '@Url.Action("GetBeverage", "Home")';
            $('.mainMenu li').removeClass('activeMenuItem');
            $('.mainMenu li[id^="@(ViewContext.Controller.ValueProvider.GetValue("action").RawValue)"]').addClass('activeMenuItem');
        });
    </script>
</head>
    <body>
        <div class="mainDiv">
        <ul class="mainMenu">
            <li id="GetBeverageItem" onclick="window.location = '@Url.Action("GetBeverage", "Home")'">Get beverage</li>
            <li id="PersonalReportItem" onclick="window.location = '@Url.Action("PersonalReport", "Report")'">Personal report</li>
            <li id="OfficeRatingsItem" onclick="window.location = '@Url.Action("OfficeRatings", "Report")'">Office raiting</li>
        </ul>
            <div class="contentDiv">
                @RenderBody()
            </div>
        </div>
    </body>
</html>